name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        xcode-version: latest-stable
    - name: xcodebuild
      run: xcodebuild clean build -project libmpdclient-ios.xcodeproj -scheme libmpdclient-ios -destination "platform=iOS Simulator,name=iPhone 11,OS=14.4" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
